name = "smartsalud-agent"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Scheduled worker - runs every hour for 48h appointment reminders
[triggers]
crons = ["0 * * * *"]

# Workers AI binding (for fallback intent detection)
[ai]
binding = "AI"

# Durable Objects
[[durable_objects.bindings]]
name = "AGENT"
class_name = "SmartSaludAgent"

[[migrations]]
tag = "v1"
new_classes = ["SmartSaludAgent"]

# Environment variables (non-secret)
[vars]
BACKEND_API_URL = "https://smartsalud-api.railway.app"
ENVIRONMENT = "production"

# Secrets (set via: wrangler secret put <KEY_NAME>)
# GROQ_API_KEY - for primary intent detection
# TWILIO_ACCOUNT_SID - for WhatsApp messaging
# TWILIO_AUTH_TOKEN - for Twilio auth
# TWILIO_WHATSAPP_NUMBER - format: whatsapp:+14155238886

# Staging environment
[env.staging]
name = "smartsalud-agent-staging"
vars = { BACKEND_API_URL = "https://smartsalud-staging.railway.app", ENVIRONMENT = "staging" }

# Development environment
[env.dev]
name = "smartsalud-agent-dev"
vars = { BACKEND_API_URL = "http://localhost:8000", ENVIRONMENT = "development" }
