name = "smartsalud-agent"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Scheduled worker - runs every hour for 48h appointment reminders
[triggers]
crons = ["0 * * * *"]

# Workers AI binding (for fallback intent detection)
[ai]
binding = "AI"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "smartsalud-db"
database_id = "5904e3c5-0c28-4f64-b14c-e2d0ca19db4a"

# Durable Objects
[[durable_objects.bindings]]
name = "AGENT"
class_name = "SmartSaludAgent"

[[durable_objects.bindings]]
name = "BROADCASTER"
class_name = "DashboardBroadcaster"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SmartSaludAgent"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["DashboardBroadcaster"]

# Environment variables (non-secret)
[vars]
ENVIRONMENT = "production"

# Secrets (set via: wrangler secret put <KEY_NAME>)
# GROQ_API_KEY - for primary intent detection
# TWILIO_ACCOUNT_SID - for WhatsApp messaging
# TWILIO_AUTH_TOKEN - for Twilio auth
# TWILIO_WHATSAPP_NUMBER - format: whatsapp:+14155238886
