name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-railway.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli

      - name: Deploy to Railway
        working-directory: ./backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service smartsalud-backend

      - name: Run migrations
        if: success()
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway run --service smartsalud-backend python manage.py migrate || echo "No migrations to run"

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Successfully deployed to Railway"
          echo "Backend URL: https://smartsalud-api.railway.app"

      - name: Health check
        if: success()
        run: |
          sleep 30
          curl -f https://smartsalud-api.railway.app/health || echo "Health check endpoint not ready"
