name: Deploy to Cloudflare

on:
  push:
    branches: [main]
    paths:
      - 'agent/**'
      - '.github/workflows/deploy-cloudflare.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Agent to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'agent/package-lock.json'

      - name: Install dependencies
        working-directory: ./agent
        run: npm ci

      - name: Build
        working-directory: ./agent
        run: npm run build || echo "No build step configured"

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: './agent'
          command: deploy

      - name: Deployment notification
        if: success()
        run: |
          echo "✅ Successfully deployed to Cloudflare Workers"
          echo "Agent URL: https://smartsalud-agent.workers.dev"

      - name: Rollback on failure
        if: failure()
        working-directory: ./agent
        run: |
          echo "❌ Deployment failed, consider manual rollback"
          # Uncomment to enable automatic rollback:
          # npx wrangler rollback --message "Auto-rollback due to deployment failure"
